name = "Modpack Template"
author = "Merith.TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b247a51ca195ef4411af41a05d5a891e5553d42d40ef1f6e12c27238866f60f"

[versions]
forge = "36.2.29"
minecraft = "1.16.5"
