name = "Patriam Golden Age"
author = "Atmos (alex), Merith.TK"
version = "6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49885ee0df71d1e2de87342e17a2a69702cc9c471c7cedf1919e5f2ddf116efe"

[versions]
forge = "36.2.29"
minecraft = "1.16.5"
